language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python manage.py test
services:
- postgresql
env:
- DB_NAME=testdb DB_USER=test DB_PASS=test DB_HOST=localhost
before_script:
- psql -U postgres -c "CREATE USER test WITH PASSWORD 'test';"
- psql -U postgres -c "ALTER USER test PASSWORD 'test';"
- psql -U postgres -c "ALTER USER test CREATEDB;"
- psql -U postgres -c "CREATE DATABASE testdb;"
- psql -U postgres -c "ALTER ROLE test superuser;"
- python manage.py collectstatic
deploy:
  provider: heroku
  app: cs3240-team-b-07
  on:
    repo: uva-cs3240-s20/project-b-07
