# Generated by Django 3.1.7 on 2021-04-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0006_auto_20210401_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='playlist',
            field=models.ForeignKey(default='no playlist', on_delete=django.db.models.deletion.SET_DEFAULT, to='hoosfit.exerciseplaylist'),
        ),
    ]
