# Generated by Django 3.1.7 on 2021-04-01 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoosfit', '0007_auto_20210401_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='playlist',
            field=models.ForeignKey(default='no playlist', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercises', to='hoosfit.exerciseplaylist'),
        ),
        migrations.AlterField(
            model_name='exerciseplaylist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
