# Generated by Django 3.1.7 on 2021-04-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0008_auto_20210401_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='playlist',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercises', to='hoosfit.exerciseplaylist'),
        ),
    ]
