# Generated by Django 3.1.7 on 2021-05-06 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosfit', '0015_auto_20210422_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='previous_workout',
            field=models.DateField(default=datetime.date(2021, 5, 5)),
        ),
    ]
